services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      NODE_ENV: production

    command: node dist/main.js

  gateway:
    restart: always

  postgres:
    restart: always

  redis:
    restart: always

  minio:
    restart: always
