services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev

    volumes:
      - ./backend:/app
      - /app/node_modules

    environment:
      NODE_ENV: development

    command: npm run start:dev

  gateway:
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/nginx/conf.d:/etc/nginx/conf.d:ro

  postgres:
    ports:
      - "5432:5432"
